import axios from "axios";

function App() {
  //   const onClick = () => {
  //     axios
  //       .get(
  //         `http://ch-patients-admission-server.gcp-hml.dasaexp.io/api/professionals/name`,
  //         {
  //           headers: {
  //             Authorization:
  //               "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTUzNDQyNTQsImtja1Rva2VuIjoiZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJZ09pQWlTbGRVSWl3aWEybGtJaUE2SUNKNlR6aHNYMFUwWjFkaVQzUm5XbEF5UlhWeVJWbFVUbGQwUnpKMlkzTTVaV1ZXVURJM1lVNWtaMmROSW4wLmV5SmxlSEFpT2pFMk1UVXpOREE1TlRRc0ltbGhkQ0k2TVRZeE5UTTBNRFkxTkN3aWFuUnBJam9pWXpsbVlUUXlOMlV0WXpsaFlTMDBaR0l6TFdFM1l6VXRNR1UwWkRFd00ySTRObUU1SWl3aWFYTnpJam9pYUhSMGNITTZMeTlwWkMxb2JXd3VaR0Z6WVM1amIyMHVZbkl2WVhWMGFDOXlaV0ZzYlhNdlJuVnVZMmx2Ym1GeWFXOXpJaXdpWVhWa0lqb2lZV05qYjNWdWRDSXNJbk4xWWlJNklqZzJNek5rTXpJeUxXWTBNbU10TkRWbVpDMDRNMlkwTFRKbFpXUm1NMk5tWlRBMVpTSXNJblI1Y0NJNklrSmxZWEpsY2lJc0ltRjZjQ0k2SW1OaGJtRnNMV2h2YzNCcGRHRnBjeUlzSW5ObGMzTnBiMjVmYzNSaGRHVWlPaUl5WVRrMVkyTmpaUzB5TldKaExUUmpZalV0T0RoaE15MWpNV0ZqWm1RNE56QTFaRFFpTENKaFkzSWlPaUl4SWl3aWNtVmhiRzFmWVdOalpYTnpJanA3SW5KdmJHVnpJanBiSW05bVpteHBibVZmWVdOalpYTnpJaXdpZFcxaFgyRjFkR2h2Y21sNllYUnBiMjRpWFgwc0luSmxjMjkxY21ObFgyRmpZMlZ6Y3lJNmV5SmhZMk52ZFc1MElqcDdJbkp2YkdWeklqcGJJbTFoYm1GblpTMWhZMk52ZFc1MElpd2lkbWxsZHkxd2NtOW1hV3hsSWwxOWZTd2ljMk52Y0dVaU9pSnZjR1Z1YVdRZ2NISnZabWxzWlNCbGJXRnBiQ0J5YjJ4bGN5SXNJbVZ0WVdsc1gzWmxjbWxtYVdWa0lqcG1ZV3h6WlN3aWJtRnRaU0k2SWxKbGJtRnVJRWhsYm5KcGNYVmxJRkpwWW1WcGNtOGdTR1Z1Y21seGRXVWdVbWxpWldseWJ5SXNJbkJ5WldabGNuSmxaRjkxYzJWeWJtRnRaU0k2SW1Zd09EZzNOVFl4TURZek1DSXNJbWRwZG1WdVgyNWhiV1VpT2lKU1pXNWhiaUJJWlc1eWFYRjFaU0JTYVdKbGFYSnZJaXdpWm1GdGFXeDVYMjVoYldVaU9pSklaVzV5YVhGMVpTQlNhV0psYVhKdklpd2laVzFoYVd3aU9pSnlaVzVoYmk1eWFXSmxhWEp2UUdSaGMyRXVZMjl0TG1KeUluMC5KZi1PY2Z4R05HakNaeC1IcDdIdVdXMzhELWFfUTBLMldNN0xOS1NRSWJtOWR5V0E0OVZlVUQtZ3ZsdGlvbTZWRXVSa0lhOXdJTG16a3hTTFV3Uy1UTlpHT1VYMnZ2NDJ0Si1mZHpWbjNmRy0xaE5tamV0QldwdGJHS1ZTaVdqT0NJdWNTa09HNWxjV1hsd0w5bVd6Ynpkd3E1LURGQk9UNjlQSUxZUjZOQ2VmSGNERGJXMXlYTDZGUm51Y1IzblZWZmVLYmtUVm1iNF9JNndKZHJrRld6QVNmMFhFN3NvUEZaU0tNWEpSc2tLNmhIOUJ2X25QX3A2UEFaZTFLT1VDcF9PaFF1VV82TU5EQ1FYa0RuMjd2Sm9vaXRNeXdBQ3FtbXBXNFJ5SmZGRDdRdkFBSzlVX3VPYWE3SjJ4S3FjUl9XYXE5UzhXWDIwc3BvYkhCRFlIVnciLCJyb2xlIjp7InJvbGVUeXBlIjoiU1VQRVJfVVNFUiIsImhpZXJhcmNoeUxldmVsIjoiMSIsImRlc2NyaXB0aW9uIjoiU3VwZXIgVXN1w6FyaW8oYSkiLCJpZCI6IjEiLCJjcmVhdGVkQXQiOiIyMDIxLTAxLTI2VDE5OjU5OjM2LjA3MFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTAxLTI2VDE5OjU5OjM2LjA3MFoifSwiY3JlYXRlZEF0IjoxNjE1MzQwNjU0NTM2LCJpYXQiOjE2MTUzNDA2NTR9.Cw6yAKjED4wPHFiMBH8uq0-JMUZePC27iGRDPVWqYFU",
  //           },
  //           params: {
  //             name: "Maria Tavares",
  //           },
  //         }
  //       )
  //       .then((resp) => {
  //         console.log(resp);
  //       });
  //   };

  const onClick = () => {
    const data = {
      name: "Renan Ribeiro",
      registryCouncil: {
        council: "CRM",
        uf: "SP",
        number: "654321",
      },
    };
    axios
      .post(`http://localhost:9090/api/professionals`, data, {
        headers: {
          Authorization:
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTU5MDg1OTUsImtja1Rva2VuIjoiZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJZ09pQWlTbGRVSWl3aWEybGtJaUE2SUNKNlR6aHNYMFUwWjFkaVQzUm5XbEF5UlhWeVJWbFVUbGQwUnpKMlkzTTVaV1ZXVURJM1lVNWtaMmROSW4wLmV5SmxlSEFpT2pFMk1UVTVNRFV5T1RVc0ltbGhkQ0k2TVRZeE5Ua3dORGs1TlN3aWFuUnBJam9pTnpVME9XRXhaREF0T0RVME1pMDBPV05oTFdKa1pUTXROalF3TXpNMU16TmlOVEU1SWl3aWFYTnpJam9pYUhSMGNITTZMeTlwWkMxb2JXd3VaR0Z6WVM1amIyMHVZbkl2WVhWMGFDOXlaV0ZzYlhNdlJuVnVZMmx2Ym1GeWFXOXpJaXdpWVhWa0lqb2lZV05qYjNWdWRDSXNJbk4xWWlJNklqZzJNek5rTXpJeUxXWTBNbU10TkRWbVpDMDRNMlkwTFRKbFpXUm1NMk5tWlRBMVpTSXNJblI1Y0NJNklrSmxZWEpsY2lJc0ltRjZjQ0k2SW1OaGJtRnNMV2h2YzNCcGRHRnBjeUlzSW5ObGMzTnBiMjVmYzNSaGRHVWlPaUl3WW1VMFpEWXlNaTFsTlRWaUxUUmlPR0l0T0RReE9DMDFZVFJpT0RWbE1qZ3hNVFFpTENKaFkzSWlPaUl4SWl3aWNtVmhiRzFmWVdOalpYTnpJanA3SW5KdmJHVnpJanBiSW05bVpteHBibVZmWVdOalpYTnpJaXdpZFcxaFgyRjFkR2h2Y21sNllYUnBiMjRpWFgwc0luSmxjMjkxY21ObFgyRmpZMlZ6Y3lJNmV5SmhZMk52ZFc1MElqcDdJbkp2YkdWeklqcGJJbTFoYm1GblpTMWhZMk52ZFc1MElpd2lkbWxsZHkxd2NtOW1hV3hsSWwxOWZTd2ljMk52Y0dVaU9pSnZjR1Z1YVdRZ2NISnZabWxzWlNCbGJXRnBiQ0J5YjJ4bGN5SXNJbVZ0WVdsc1gzWmxjbWxtYVdWa0lqcG1ZV3h6WlN3aWJtRnRaU0k2SWxKbGJtRnVJRWhsYm5KcGNYVmxJRkpwWW1WcGNtOGdTR1Z1Y21seGRXVWdVbWxpWldseWJ5SXNJbkJ5WldabGNuSmxaRjkxYzJWeWJtRnRaU0k2SW1Zd09EZzNOVFl4TURZek1DSXNJbWRwZG1WdVgyNWhiV1VpT2lKU1pXNWhiaUJJWlc1eWFYRjFaU0JTYVdKbGFYSnZJaXdpWm1GdGFXeDVYMjVoYldVaU9pSklaVzV5YVhGMVpTQlNhV0psYVhKdklpd2laVzFoYVd3aU9pSnlaVzVoYmk1eWFXSmxhWEp2UUdSaGMyRXVZMjl0TG1KeUluMC5Ea2pIdWNJREFqcTY3YThIRUJsVFAzdnFacHFsNWJXLXMyYzNMNGJHek5YaHM2TzdIZHNxbmVDOEhoUlZENGFVS3lZT3huT0R5SUNmZkQtWU5VS2NUT2FfVmhSUHByLWVhcVZqS05FcjVSN250SWpTYkhPaUsxVVpXeHFSQmdlNzFGWVVHM3dlUmgwV3FqN3hYU2JhcWhCSnVCTVUzLVR5MTV0THVqMXAzYVRQSUU4Y2xSbkhzdllCOVhHS3hVSzBMd0o0MHlibzBkWVBGcUluVHN6Ti0tNlF3TzRlSWw2cGR6c3FyUUdDWjc2bjUxN0VSVU5wY2pVLUZia2VOUURoREtXN3BkYUlaYlpybHJldml6MGZuUTNIb1l4SktsSkxEa3NLa3J6OHdhOGgtTG9lUHNuam1DMlR0Y0dxcktjUFdhcGpHd2lEOTBFY3hUM2xqUy1XMEEiLCJyb2xlIjp7InJvbGVUeXBlIjoiU1VQRVJfVVNFUiIsImhpZXJhcmNoeUxldmVsIjoiMSIsImRlc2NyaXB0aW9uIjoiU3VwZXIgVXN1w6FyaW8oYSkiLCJpZCI6IjEiLCJjcmVhdGVkQXQiOiIyMDIxLTAxLTI2VDE5OjU5OjM2LjA3MFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTAxLTI2VDE5OjU5OjM2LjA3MFoifSwiY3JlYXRlZEF0IjoxNjE1OTA0OTk1MTg0LCJpYXQiOjE2MTU5MDQ5OTV9.QsXIY0QMhYN2MbaEYZO6YmkO5M4WT78HiJ4EKBE1VUo",
        },
      })
      .then((resp) => {
        console.log(resp);
      });
  };

  return <button onClick={onClick}>Teste</button>;
}

export default App;
